return {
	systems = {
		{
			name = "ONYX",
			protocol = "kocos",
			kernel = "vmkocos",
			ramfs = "ramimg-kocos.kar",
			cmdline = "",
		},
		{
			name = "ONYX (Debug)",
			protocol = "kocos",
			kernel = "vmkocos",
			ramfs = "ramimg-kocos.kar",
			cmdline = "",
		},
	},
}
